"""initial_schema

Revision ID: 29b5ccadf8fc
Revises: 
Create Date: 2026-05-09 08:56:46.160369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29b5ccadf8fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ai_recipes_user', table_name='ai_recipe_history')
    op.drop_constraint('conversations_participant_1_participant_2_key', 'conversations', type_='unique')
    op.drop_index('idx_diet_plans_assigned_to', table_name='diet_plans')
    op.drop_constraint('dietician_client_links_dietician_id_client_id_key', 'dietician_client_links', type_='unique')
    op.drop_index('idx_food_items_barcode', table_name='food_items')
    op.drop_index('idx_food_items_category', table_name='food_items')
    op.drop_index('idx_food_items_name_search', table_name='food_items', postgresql_using='gin')
    op.alter_column('food_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_food_logs_user_date', table_name='food_logs')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_index('idx_reports_user', table_name='reports')
    op.alter_column('water_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('weight_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weight_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('water_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_reports_user', 'reports', ['user_id', 'report_type', sa.text('start_date DESC')], unique=False)
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', sa.text('sent_at DESC')], unique=False)
    op.create_index('idx_food_logs_user_date', 'food_logs', ['user_id', sa.text('logged_at DESC')], unique=False)
    op.alter_column('food_logs', 'logged_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('idx_food_items_name_search', 'food_items', [sa.text("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_food_items_category', 'food_items', ['category_id'], unique=False)
    op.create_index('idx_food_items_barcode', 'food_items', ['barcode'], unique=False)
    op.create_unique_constraint('dietician_client_links_dietician_id_client_id_key', 'dietician_client_links', ['dietician_id', 'client_id'])
    op.create_index('idx_diet_plans_assigned_to', 'diet_plans', ['assigned_to'], unique=False)
    op.create_unique_constraint('conversations_participant_1_participant_2_key', 'conversations', ['participant_1', 'participant_2'])
    op.create_index('idx_ai_recipes_user', 'ai_recipe_history', ['user_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###
